apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  labels:
    app.kubernetes.io/instance: crossplane-dev
  name: foocompany1.buckets.a-bucket
spec:
  forProvider:
    region: us-west-2
  providerConfigRef:
    name: default
